# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 31526
subtitle: javascript es6
description:
author: 31526
email: 31526@qq.com
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults: en


Plugins:
- hexo-qiniu-sync
- hexo-generator-feed
- hexo-generator-sitemap
- hexo-generator-baidu-sitemap

#sitemap
sitemap:
  path: sitemap.xml


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: default
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next #landscape


# =============================================================================
# NexT Theme configuration
# =============================================================================

avatar: http://7xnift.com1.z0.glb.clouddn.com/img/2015/github-io-avarar.jpg

# avatar: https://avatars1.githubusercontent.com/u/32269?v=3&s=460

# Duoshuo
duoshuo_shortname: 31526

# Disqus
disqus_shortname:


# Social links
social:
  GitBlog: http://31526.github.io
  CafeBlog: http://31526.gitcafe.io
  GitHub: https://github.com/31526
  GitCafe: https://gitcafe.com/31526
  Twitter: https://twitter.com/31526
  Weibo: http://weibo.com/31526
  DouBan: http://douban.com/people/31526
  ZhiHu: http://www.zhihu.com/people/31526


baidusitemap:
    path: baidusitemap.xml




#七牛云存储设置
##域名 7xnift.com1.z0.glb.clouddn.com
##offline       是否离线. 离线状态将使用本地地址渲染
##sync          是否同步
##bucket        空间名称.
##access_key    上传密钥AccessKey
##secret_key    上传密钥SecretKey
##dirPrefix     上传的资源子目录前缀.如设置，需与urlPrefix同步
##urlPrefix     外链前缀.
##local_dir     本地目录.
##update_exist  是否更新已经上传过的文件(仅文件大小不同或在上次上传后进行更新的才会重新上传)
##image/js/css  子参数folder为不同静态资源种类的目录名称，一般不需要改动
##image.extend  这是个特殊参数，用于生成缩略图或加水印等操作。具体请参考http://developer.qiniu.com/docs/v6/api/reference/fop/image/
##              可使用基本图片处理、高级图片处理、图片水印处理这3个接口。例如 ?imageView2/2/w/500 即生成宽度最多500px的缩略图
qiniu:
  offline: false
  sync: true
  bucket: github
  access_key: YRUQQ21TxlUd_VWZUNEkKu4pP3tNap5-Qn_0aNuE
  secret_key: V8Rezrp57_Omm4p4z61HHq55PNr5o7xx8fwBnYi0
  dirPrefix:
  urlPrefix: http://7xnift.com1.z0.glb.clouddn.com
  local_dir: static
  update_exist: true
  image:
    folder: img
    extend:
  js:
    folder: js
  css:
    folder: css





# Creative Commons 4.0 International License.
# http://creativecommons.org/
# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
creative_commons: by-nc-sa


# Swiftype 搜索
# 使用 Swiftype 之前需要前往 Swiftype 配置一个搜索引擎。
# 然后，编辑 站点配置文件，新增 swiftype_key 字段，值为你的 swiftype 搜索引擎的 key。
swiftype_key: p3PDwVtc34s7Cawy_enq


# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
# Google Analytics
# Google分析ID
# google_site_verification: VvyjvVXcJQa0QklHipu6pwm2PJGnnchIqX7s5JbbT_0
google_analytics:



# 百度分析ID
baidu_analytics: 50c15455e37f70aea674ff4a663eef27

# Specify the date when the site was setup
since: 2011

# =============================================================================
# End NexT Theme configuration
# =========================



index_generator:
  per_page: 10

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 20


# Deployment
## Docs: http://hexo.io/docs/deployment.html
# Example:
#   deploy:
#     type: git
#     repo: <repository url>
#     branch: [branch]
#     message: [message]


# # # # 多部署
# # deploy:
# #   type: git
# #   message: update  ##git message建议默认字段update 可以自定义
# #   repo:
# #   gitcafe: <repository url>,[branch] ##gitcafe 仓库地址和分支
# #   github: <repository url>,[branch] ##github 仓库地址和分支

# deploy:
#   type: git
#   messgae: "update"
#   repo:
#     github: git@github.com:31526/31526.github.io.git  master
#     gitcafe: git@gitcafe.com:31526/31526.git  gitcafe-pages



# deploy:
#   type: git
#   #messgae: "update"
#   # repository: git@gitcafe.com:31526/31526.git
#   # branch: master

#   repository: git@github.com:31526/31526.github.io.git
#   branch: master


# # # # 多部署

# deploy:
#   type: git
#   repository: git@github.com:31526/31526.github.io.git
#   branch: master

deploy:
  type: git
  repository: git@gitcafe.com:31526/31526.git
  branch: gitcafe-pages



